Repository CMU-313/nodebb-f24-slackers, pull requests merged in 2024-10, with the labels that each got.

#30 Added UserGuide template and filled in some information
  UserGuide.md
Labels: documentation

#32 UnVerify API Tests
  dump.rdb
  nodebb-theme-slackers/templates/partials/topic/post-menu-list.tpl
  test/posts.js
Labels: Message verified function

#34 Set up permissions for verify and unverify and UI for unverify
  UserGuide.md
  dump.rdb
  nodebb-theme-slackers/templates/partials/topic/post-menu-list.tpl
  nodebb-theme-slackers/templates/partials/topic/post.tpl
  src/api/posts.js
  test/posts.js
Labels: Message verified function

#36 Answer post UI
  .github/workflows/f24_nodebb-yerim-test.yml
  nodebb-theme-slackers/templates/partials/topic/topic-menu-list.tpl
  nodebb-theme-slackers/templates/partials/topics_list.tpl
  nodebb-theme-slackers/templates/topic.tpl
  public/language/en-GB/topic.json
  public/language/en-US/topic.json
  public/language/en-x-pirate/topic.json
  public/openapi/components/schemas/TopicObject.yaml
  public/openapi/read/tags/tag.yaml
  public/openapi/write.yaml
  public/openapi/write/topics/tid/answer.yaml
  public/src/client/category/tools.js
  public/src/client/topic/events.js
  public/src/client/topic/posts.js
  public/src/client/topic/threadTools.js
  public/src/modules/helpers.common.js
  src/api/topics.js
  src/controllers/write/topics.js
  src/privileges/posts.js
  src/privileges/topics.js
  src/routes/write/topics.js
  src/topics/create.js
  src/topics/data.js
  src/topics/events.js
  src/topics/index.js
  src/topics/posts.js
  src/topics/tools.js
  test/template-helpers.js
  test/topics.js
Labels: Question Answered Functionality
